### ISSUE TITLE
Update To Work With Latest O3DE Development Branch

### ISSUE THREAD

**Issue by santorac** [PopcornFX/O3DEPopcornFXPlugin#19]
In support of ongoing O3DE development and in preparation for the next release, the PopcornFX integration needs to be updated to work with recent O3DE API changes. I recently tried using 2.12.7 with the O3DE development branch and encountered the following issues.

1. The SCRIPT_CANVAS_PERFORMANCE_SCOPE_LATENT macro parameters have changed. I commented it out locally in PopcornFXBroadcastNodeable::OnEmitterBroadcastEvent().
2. Several of the "_Legacy" shaders no longer compile, due to changes related to shadowCoords, GetShadowCoords, and ApplyDirectLighting. (see https://github.com/o3de/o3de/pull/8312)
3. The PopcornFXEmitterEditorComponent::GetAttributeAsFloat[2-4] functions don't compile in debug mode, due to warnings about uninitialized "value" variable.

**Comment by ValPKFX** [comment]
Thank you for the report.
This is now fixed with the PR #20 and #21.
