### ISSUE TITLE
PopcornFX assert/crash in Game launcher

### ISSUE THREAD

**Issue by AMZN-Olex** [PopcornFX/O3DEPopcornFXPlugin#30]
We have a setup with 49 ai characters running and shooting which results in a particle effects. In the Editor that works fine
but in the game launcher it asserts with:

![image](https://user-images.githubusercontent.com/5432499/203659611-19782f48-5ec4-45a2-bd99-22d123b459ba.png)

The log shows:
```
The thread 0x71dc has exited with code 0 (0x0).
[WARN][Kernel|ThreadPool]> CParticleUpdater_CPU::UpdateFence is taking too long (1st time) (PopcornFX::Threads::CAbstractPool*)0x0000018A09A79BF8
<16:47:03> [Warning] (System) - Processing time exceeded, discarding 919/1024 received packets
[ERR1][O3DE]> !! PopcornFX Assertion failed !!
File       : A:\full-rebuild\source_tree\Runtime\pk_particles\src\Mediums\mediums_collection.cpp(1214)
Function   : PopcornFX::CParticleMediumCollection::_IncrementEffectIDRefsIFN(...)
Condition  : (effectSOA_StateData[rawID.ToIndex()] & CEffectInstanceData::StateDataBit_KillSwitch) == 0
ThreadID   : 1
AssertNum  : 1
```

In the Editor it is working well for us:
https://user-images.githubusercontent.com/5432499/203659843-3f660f76-e47d-4be0-bad9-c2cc968213f0.mp4

**Comment by ValPKFX** [comment]
This is now fixed on the development branch and will be fixed in the 2.14.4 gem release.
Thank you for reporting.
