### ISSUE TITLE
Calling Kill() on the first tick puts particle emitters in a permanent undead state

### ISSUE THREAD

**Issue by mbalfour-amzn** [PopcornFX/O3DEPopcornFXPlugin#42]
If Kill() is called on a particle effect on the first tick, it will never make it to an OnDeath() state and so any calls to Restart() will get stuck waiting for the death to occur. If Kill() is called any time after the first tick, it seems to work correctly.

The attached level (created inside of the MultiplayerSample project) has a Script Canvas script that exposes the number of ticks to wait before calling Kill(), the number of ticks before calling Restart(), and the total number of ticks before looping. When the kill ticks is set to 1 (the first tick), the ball never appears. When it is set to 2, the ball disappears and reappears correctly.

This problem can be worked around either by using Restart(false) (to call terminate instead of Kill) and/or using Terminate() instead of Kill() to stop the effect, but calling Kill() on the first frame ought to work.

[ParticleClientOnly.zip](https://github.com/o3de/o3de-multiplayersample/files/11256329/ParticleClientOnly.zip)

**Comment by ValPKFX** [comment]
Thank you for the repro case, it was really helpful.
It is indeed an issue in the PopcornFX runtime, it will be fixed in the next releases next week (2.15.7 and 2.16.2).

**Comment by ValPKFX** [comment]
This is resolved in the 2.15.7 and 2.16.2 releases.
