### ISSUE TITLE
Compile Error: 'GetBufferView': is not a member of 'AZ::RHI::Buffer' 

### ISSUE THREAD

**Issue by AMZN-Gene** [PopcornFX/O3DEPopcornFXPlugin#75]
PopcornFx Gem is failing to compile using latest O3DE development branch.

**Repro Steps**
1. Pull latest O3DE development branch
2. Build project which uses popcorn fx

**Expected Results**
Project builds successfully

**Actual Results**
The Atom AZ::RHI::Buffer API has changed such that PopcornFx no longer compiles.

```
\Gems\O3DEPopcornFXPlugin\Code\Source\Integration\Render\AtomIntegration\BillboardBatchDrawer.cpp(357,63): error C2039: 'GetBufferView': is not a member of 'AZ::RHI::Buffer'
```

**Comment by ValPKFX** [comment]
Thank you for the report.
This is now fixed on the development branch of the gem and will be included in the next releases.
