### ISSUE TITLE
O3DE Development Branch Compilation error

### ISSUE THREAD

**Issue by spham-amzn** [PopcornFX/O3DEPopcornFXPlugin#77]
A recent update to https://github.com/o3de/o3de in the development branch breaks the O3DE Popcorn FX plugin based on commit 69979c633caa641dc8a3fc25674f136256f73781 in https://github.com/PopcornFX/O3DEPopcornFXPlugin and produces the following build error:

```
130>D:\github\o3de-multiplayersample-assets\Gems\O3DEPopcornFXPlugin\Code\Source\Integration\Managers\RenderManager.cpp(58,49): error C2248: 'AZ::RHI::BufferPool::Init': cannot access private member declared in class 'AZ::RHI::BufferPool'
```
This was caused by a header file change in the Atom Gem:
https://github.com/o3de/o3de/pull/18133 

Attached is a patch file that I used to get around the issue

[popcorn_fx_fix.patch](https://github.com/user-attachments/files/16446649/popcorn_fx_fix.patch)

**Comment by ValPKFX** [comment]
Thank you.
This is now pushed on the development branch.
